import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Header} from '../components/navigation/Header';
import {Footer} from "@/components/footer/Footer"
import { CartProvider } from '@/context/CartContext';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="max-w-screen-2xl  mx-auto ">
      <CartProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       
       >
        <Header />
        {children}
        <Footer/>
        
      </body>
        </CartProvider>
    </html>
  );
}
